config/routes.rb
Fingerball::Application.routes.draw do

  

     namespace :admin do
       resources :users
     end
end

app/models/concerns/user_attribute_ext.rb
module UserAttributeExt
  extend ActiveSupport::Concern

  included do |klass|
    belongs_to :user
  end

  module ClassMethods

    def registered_attr_types
      ["last_activity_time", "last_activity_action"]
    end

    def build_base_collection(entity)
      result = []
      registered_attr_types.each do |attr_type|
        result << UserAttribute.new(:attribute_type => attr_type, :value => "")
      end
      return result
    end

  end

end

app/models/concerns/user_ext.rb
module UserExt
  extend ActiveSupport::Concern

  included do
    scope :active, -> {where(is_active: 1)}
    scope :players, -> {where(user_type: UserType::Player.key)}
    scope :managers, -> {where(user_type: UserType::Manager.key)}
    has_many :stats, :class_name => "UserStat", :dependent => :destroy
    has_many :user_attributes, :dependent => :destroy
    before_save :prepare_base_user
  end

  #instance methods

  def user
    self.user_type.constantize.new(self)
  end

  def user=(user_instance)
    self.user_type = user_instance.class
  end

  protected

  def prepare_base_user
    self.transaction do
      prepare_stats
      prepare_attrs
    end
  end

  def prepare_stats
    self.stats << UserStatType::StatTypeListener.get_instance.build_base_stats_collection(self) if self.id.nil? && self.stats.empty?
    self
  end

  def prepare_attrs
    self.user_attributes << UserAttribute.build_base_collection(self) if self.id.nil? && self.user_attributes.empty?
    self
  end

  module ClassMethods
    #class methods

  end

end

app/models/concerns/user_stat_ext.rb
module UserStatExt
  extend ActiveSupport::Concern

  included do |klass|
    belongs_to :user
  end

  module ClassMethods

  end

end

app/models/concerns/user_stat_type/base.rb
class UserStatType::Base

  attr_accessor :user

  def initialize(user)
    self.user = user
  end

end

app/models/concerns/user_stat_type/power.rb
class UserStatType::Power < UserStatType::Base

end

app/models/concerns/user_stat_type/stat_type_listener.rb
class UserStatType::StatTypeListener

  attr_accessor :classes

  def self.get_instance
    @stat_listener ||= UserStatType::StatTypeListener.new
  end

  def classes
    ["UserStatType::Strength", "UserStatType::Power"]
  end

  def build_base_stats_collection(entity)
    result = []
    self.classes.each do |klass|
      result << UserStat.new(:stat_type => klass)
    end
    result
  end

  private

  def initialize
    #@stat_listener ||= UserStatType::StatTypeListener.new
    #@stat_listener
  end

end

app/models/concerns/user_stat_type/strength.rb
class UserStatType::Strength < UserStatType::Base

end

app/models/concerns/user_type/base.rb
class UserType::Base

  attr_accessor :user, :key

  def initialize(user)
    self.user = user
    self.key = 'player'
  end

end

app/models/concerns/user_type/manager.rb
class UserType::Manager < UserType::Base

  def initialize(user)
    self.key = "manager"
    super(user)
  end

  def self.key
    "manager"
  end

end

app/models/concerns/user_type/player.rb
class UserType::Player < UserType::Base

  def initialize(user)
    self.key = 'player'
    super(user)
  end

  def self.key
    "player"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include UserExt


end

app/models/user_attribute.rb
class UserAttribute < ActiveRecord::Base
  include UserAttributeExt
end

app/models/user_stat.rb
class UserStat < ActiveRecord::Base
  include UserStatExt
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(@user, :url => {:controller => "admin/users"}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', admin_user_path(user) %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', "/admin/users/destroy/#{user.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fingerball</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>